debug: false
name: Loan Officers portal
monolog.config:
    monolog.name:    loportal
    monolog.logfile: logs/prod.log
    monolog.level:   DEBUG
orm.em.options:
    mappings:
      0:
        type: "annotation"
        namespace: "LO\\Model\\Entity"
        path: "%base_path%/src/LO/Model/Entity"

db.options:
    driver:   pdo_mysql
    host:     aatkmlh9y3txxy.c0hzddsu3ovk.us-east-1.rds.amazonaws.com
    dbname:   ebdb
    user:     loportal
    password: GPz3quD4YXK7aaY9
    charset:  utf8
user:
    token.expire: 5 # 5 days
    recovery.password.expire.days: 1 # 1 day
firstrex:
  api:
    user: FirstREX
    pass: Admin007
    url: http://tools.1rex.com/inquiries.json
  additional.emails:
    - joanna.umali@1rex.com
google:
  apiKey: NotPresent
amazon:
    securityCredentials:
      key:    AKIAJGGPNM46RAXZIFDA
      secret: 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
      region: us-east-1
    ses:
      securityCredentials:
        key: AKIAIINCG3J7RCRMROOA
        secret: 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
        region: us-east-1
      source: rexinfo12@gmail.com

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: pagination.twig,
        sortable:   Pagination/sortable_link.html.twig