debug: false
name: Loan Officers portal
monolog.config:
    monolog.name:    loportal
    monolog.logfile: logs/prod.log
    monolog.level:   WARNING
    isSaveLocal:     false
    s3.logs: s3://1rex.app/prod.log
orm.em.options:
    mappings:
      0:
        type: "annotation"
        namespace: "LO\\Model\\Entity"
        path: "%base_path%/src/LO/Model/Entity"

db.options:
    driver:   pdo_mysql
    host:     aa1h5guh7x79vai.c0hzddsu3ovk.us-east-1.rds.amazonaws.com
    dbname:   ebdb
    user:     loportal
    password: GPz3quD4YXK7aaY9
    charset:  utf8
user:
    token.expire: 5 # 5 days
    recovery.password.expire.days: 1 # 1 day
firstrex:
  api:
    user: FirstREX
    pass: Admin007
    url: http://tools.1rex.com/inquiries.json
  additional.emails:
    - joanna.umali@1rex.com
  email:
    teplate:
      denial: joanna.umali@1rex.com
google:
  apiKey: AIzaSyAxuigzKpMper8uWzvQYdHI6lQJm4f26JM
  analytics: UA-63817823-1
amazon:
    securityCredentials:
      key:    AKIAJGGPNM46RAXZIFDA
      secret: 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
      region: us-west-1
    ses:
      securityCredentials:
        key: AKIAIINCG3J7RCRMROOA
        secret: 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
        region: us-west-1
      source: rexinfo12@gmail.com

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: pagination.twig,
        sortable:   Pagination/sortable_link.html.twig