debug: false
name: Black Jack with comrades
monolog.config:
    monolog.name:    bdcards-mail
    monolog.logfile: /var/www/bjm-web/shared/logs/prod.log
    monolog.level:   DEBUG
email:
  subject: sent you a Blackjack with Comrades request
  body: |
        I challenge you, Comrade, to a game of Blackjack. There's no way you can win.
        http://goo.gl/qrOVX9