debug: false
name: Loan Officers portal
monolog.config:
    monolog.name:    bdcards-mail
    monolog.logfile: /var/www/bjm-web/shared/logs/prod.log
    monolog.level:   DEBUG
orm.em.options:
    mappings:
      0:
        type: "annotation"
        namespace: "LO\\Model\\Entity"
        path: "%base_path%/src/LO/Model/Entity"

db.options:
    driver:   pdo_mysql
    host:     localhost
    dbname:   loportal
    user:     loportal
    password: GPz3quD4YXK7aaY9
    charset:  utf8
user:
    token.expire: 5 # 5 days