debug: true
name: STAGE Loan Officers portal
monolog.config:
    monolog.logfile: ../logs/stage.log
    monolog.level:   DEBUG
    s3.logs: s3://1rex/app/stage.log
db.options:
    driver:   pdo_mysql
    host:     aaf7mknlkrfibf.cc4h8hidbkl4.us-west-1.rds.amazonaws.com
    dbname:   ebdb
    user:     loportal
    password: GPz3quD4YXK7aaY9
    charset:  utf8
google:
  apiKey: AIzaSyCvs5PnZWvzQlQAmlBdR24YGhkfgFavF6I
  analytics: UA-63916987-1
amazon:
    securityCredentials:
      key:    AKIAIDYXBAKHZD5BUYVQ
      secret: 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
      region: us-west-1
    ses:
      securityCredentials:
        key: AKIAJEUQ76HEF5BQPUUQ
        secret: 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
        region: us-east-1
      source: development@1rex.com
firstrex:
  doSend: false
  api:
    url:  http://tools.1rex.com:3000/inquiries.json
  additional.emails:
    - serhii.samoilenko@appsorama.com
    - dmitry@appsorama.com