debug: true
name: STAGE Loan Officers portal
monolog.config:
    monolog.logfile: ../logs/stage.log
    monolog.level:   DEBUG
    s3.logs: s3://1rex.app/stage.log
db.options:
    driver:   pdo_mysql
    host:     aawzleztuiykms.c0hzddsu3ovk.us-east-1.rds.amazonaws.com
    dbname:   ebdb
    user:     loportal
    password: GPz3quD4YXK7aaY9
    charset:  utf8
google:
  apiKey: AIzaSyAWiNe3wNoy0kh1WOVgHcPGPJ65ukBwBu0
  analytics: UA-63916987-1
amazon:
    securityCredentials:
      key:    AKIAJGGPNM46RAXZIFDA
      secret: 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
firstrex:
  api:
    url:  http://tools.1rex.com:3000/inquiries.json
  additional.emails:
    - serhii.samoilenko@appsorama.com