configure::basepath: /var/www/vhosts/broadwaytenniscenter.com/current
configure::vhost: broadwaytenniscenter.com
configure::percona_password: GPz3dul78vofXaY9

configure::stripe_api_key: sk_live_bDY47AlLyuw0OzzukAKjy30H
configure::stripe_api_publishable: pk_live_CmEcShBllyirAyQbF3qBrk1t

configure::paypal_mode: live
configure::paypal_client_id: AbRHQmsXVaQFP4ZSoP9h-M5t4y960HrjnPl4CpkXjDam8DNuYVkjUDXjp-c-f-l9O1eBK3Mxx3eULCYe
configure::paypal_client_secret: EGgXAk_BUF995sGkt169A6FqcBb-DM7g1jM-k_7lg4NRoqjMW-Jzg3GoYAw4VMmKWQvS2zveJ5LkVfZH

configure::facebook_app_id: 1556606621247060
configure::facebook_app_secret: d1b84312b365c390092a77a1bc32b23e