
configure::basepath: /vagrant
configure::vhost: vagrant.lo-portal.com

configure::owner: games
configure::group: games
#configure::facebook_app_id: 1556609001246822
#configure::facebook_app_secret: 4e1e44bd5049e6263483ba211944be8f

configure::percona_password: GPz3quD4YXK7aaY9

#configure::config_path: "%{hiera('configure::basepath')}/config/services.json"

apache::vhosts:
  "%{hiera('configure::vhost')}":
    port: 80
    docroot: "%{hiera('configure::basepath')}/web/"
    docroot_owner: 501
    docroot_group: games
    priority: 1
    override: All
    serveraliases:
      - "%{hiera('configure::vhost')}"

#  "ssl.%{hiera('configure::vhost')}":
#    servername: "%{hiera('configure::vhost')}"
#    port: 443
#    docroot: "%{hiera('configure::basepath')}/web/"
#    docroot_owner: 501
#    docroot_group: games
#    priority: 1
#    override: All
#    ssl: true
#    ssl_cert: /etc/ssl/cert.pem
#    ssl_chain: /etc/ssl/bundle.crt
#    serveraliases:
#      - "%{hiera('configure::vhost')}"

php::module:
  opcache:
    ensure: installed
  pecl-xdebug:
    ensure: installed
  process:
    ensure: installed
  xml:
    ensure: installed
  pdo:
    ensure: installed
  mcrypt:
    ensure: installed
  mbstring:
    ensure: installed
  pear:
    ensure: installed
  pear-DB:
    ensure: installed
  pecl-apc:
    ensure: installed
  pecl-imagick:
    ensure: installed

php::module::ini:
  opcache:
    settings:
      opcache.enable: 1
      opcache.enable_cli: 0
      opcache.memory_consumption: 128
      opcache.interned_strings_buffer: 16
      opcache.max_accelerated_files: 4000
      opcache.revalidate_freq: 2
      opcache.validate_timestamps: 1
  pecl-xdebug:
    settings:
      xdebug.remote_host: "10.0.2.2"
      xdebug.remote_port: 9000
      xdebug.max_nesting_level: 100
      xdebug.remote_enable: 1
      xdebug.idekey: "PHPSTORM"
      xdebug.remote_autostart: 1